### ISSUE TITLE
Проваливаются проверки заданий студентов

### ISSUE THREAD

**Issue by Sapunov** [Sapunov/edujudge#28]
```
10:23:25 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
10:23:25 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
10:23:25 ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/var/www/app/judge/api/testsystem.py", line 155, in test_solution
    solution.task.test_checker_path)
  File "/var/www/app/judge/api/testsystem.py", line 91, in match_solution_with_checker
    if not run_checker(test_input, test_output, user_output, checker_path):
  File "/var/www/app/judge/api/testcheckers.py", line 78, in run_checker
    ok, module_or_error, script_name = load_module(checker_path, check=False)
  File "/var/www/app/judge/api/testcheckers.py", line 35, in load_module
    module_path, script = path_to_script.rsplit('/', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/var/www/app/judge/api/testsystem.py", line 155, in test_solution
    solution.task.test_checker_path)
  File "/var/www/app/judge/api/testsystem.py", line 91, in match_solution_with_checker
    if not run_checker(test_input, test_output, user_output, checker_path):
  File "/var/www/app/judge/api/testcheckers.py", line 78, in run_checker
    ok, module_or_error, script_name = load_module(checker_path, check=False)
  File "/var/www/app/judge/api/testcheckers.py", line 35, in load_module
    module_path, script = path_to_script.rsplit('/', 1)
ValueError: not enough values to unpack (expected 2, got 1)
10:23:25 Invoking exception handler <bound method Worker.move_to_failed_queue of <rq.worker.Worker object at 0x7fa428d5c358>>
10:23:25 Moving job to 'failed' queue
```

**Comment by Sapunov** [comment]
Почему-то в `test_checker_path` была пустая строка вместо `None`. Как она туда попала неизвестно. Сделал поля в модели `default=None` и `blank=False`
